### ISSUE TITLE
请问有无 lutpack 相关的论文

### ISSUE THREAD

**Issue by phyzhenli** [wjrforcyber/ABCPaperCheck#3]
好像没有 lutpack 相关的论文，请问有无这类论文可以上传？

**Comment by wjrforcyber** [comment]
原文更新了，你看看。
另外应该还有一份长篇的report我看过但是我找不到了暂时，找到了到时候at你。

**Comment by phyzhenli** [comment]
我也是做逻辑综合的，请问可以认识一下嘛？我的微信号是 imzli_
